version: '3'

services:
  db:
    build: 
      dockerfile: deployments/docker/database/Dockerfile
      context: .
    expose:
      - "5432"
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  wallet:
    build: 
      dockerfile: deployments/docker/wallet/Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: "8080"
      SERVER_HOST: wallet
      DATABASE_HOST: db
      DATABASE_PORT: "5432"
      DATABASE_NAME: wallet
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      - db
