# Application server settings
server:
  host: "localhost"
  port: "8080"

# Database (Postgres) settings
database:
  host: "localhost"
  port: "5433"
  database: "wallet"
  username: "postgres"
  password: "postgres"
  ssl: "disable"
  conn-wait: yes
  conn-pool: 5